"""Resumable build identity and state persistence adapters."""

from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping


@dataclass(frozen=True)
class BuildStateDependencies:
    bindings: Mapping[str, object]

    @classmethod
    def bind(cls, **bindings):
        return cls(MappingProxyType(dict(bindings)))

    def __getattr__(self, name):
        try:
            return self.bindings[name]
        except KeyError as error:
            raise AttributeError(name) from error


def _parse_file_records(text, deps=None):
    """Parse a build-generation reply into file objects without repairing cuts.

    The primary contract is one per-file JSON object per line. The parser is
    deliberately tolerant of harmless formatting and deliberately intolerant of
    unsafe salvage:
      * a record must begin its line, so prose examples are not accepted;
      * objects may be pretty-printed or concatenated on one line;
      * an unterminated object is treated as a truncated tail and dropped;
      * a legacy {"files":[...]} wrapper is unwrapped after a full decode.
    """
    _build_workflow = deps._build_workflow
    return _build_workflow.parse_file_records(text)


def _within_root(child_real, root_real, deps=None):
    """True if realpath `child_real` is inside (or equal to) `root_real`. Uses
    commonpath so it is correct even when root_real is the filesystem root '/'
    (M9: `child.startswith(root + os.sep)` fails there — nothing starts with
    '//', wrongly rejecting every subdirectory)."""
    _build_workflow = deps._build_workflow
    return _build_workflow.within_root(child_real, root_real)


def safe_relpath(path, root, deps=None):
    """Path-traversal firewall for manifest writes. Model
    output is UNTRUSTED: any path it names must resolve to a plain relative
    location strictly inside `root`, or be rejected VERBATIM with a reason —
    never 'fixed' (fixing invites smuggling). Blocks the zip-slip family:
    absolute paths, drive/UNC prefixes, .. segments, ~ references, .git
    internals, credential-named files, control characters, and symlinked
    ancestors/destinations that physically escape the root. Returns the
    normalized relative path or raises ValueError."""
    SECRET_NAMES_RE = deps.SECRET_NAMES_RE
    _build_workflow = deps._build_workflow
    return _build_workflow.safe_relative_path(
        path, root, secret_name_re=SECRET_NAMES_RE)


def _build_state_path(root, deps=None):
    _build_workflow = deps._build_workflow
    return _build_workflow.state_path(root)


def build_resume_identity(*, task, model, reduce_model, context_paths,
                          raw_context_sha, max_files, max_file_bytes,
                          max_tokens, temperature, deps=None):
    """Hash every stable input that can change generated build content.

    Include the runtime version so prompt/repair changes in a plugin update do
    not silently reuse files generated by an older pipeline. This identity is
    separate from the on-disk state format version.
    """
    __version__ = deps.__version__
    _build_workflow = deps._build_workflow
    return _build_workflow.resume_identity(
        runtime_version=__version__, task=task, model=model, reduce_model=reduce_model,
        context_paths=context_paths, raw_context_sha=raw_context_sha,
        max_files=max_files, max_file_bytes=max_file_bytes,
        max_tokens=max_tokens, temperature=temperature)


def _save_build_state(root, state, deps=None):
    """Atomic 0600 resume-state write; best-effort (a state failure must never
    kill a run whose results are already in memory)."""
    _build_state_path = deps._build_state_path
    json = deps.json
    os = deps.os
    sys = deps.sys
    tempfile = deps.tempfile
    try:
        os.makedirs(root, exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=root, prefix=".ambient-build-")
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(state, fh)
        os.replace(tmp, _build_state_path(root))
        os.chmod(_build_state_path(root), 0o600)
    except OSError as err:
        print(f"ambient: could not save build resume-state ({err})",
              file=sys.stderr)


def _load_build_state(root, task_sha, max_plan=512, max_file_bytes=None, deps=None):
    """Resume state is UNTRUSTED data (any process could have written it):
    every path re-fires through the firewall and every record's hash is
    re-verified, or the state is discarded — a poisoned state file must not
    become a --dir escape on the next --apply. task_sha matching is cache
    IDENTITY, not integrity, so the user's own caps are re-enforced against the
    loaded state: `max_plan` (= --max-files) bounds BOTH the accepted plan items
    AND the resumed `done` files, and `max_file_bytes` (= --max-file-bytes)
    drops any over-cap resumed file — a same-hash poisoned state cannot apply
    more or bigger files than the current invocation allows."""
    _build_state_path = deps._build_state_path
    _build_workflow = deps._build_workflow
    json = deps.json
    safe_relpath = deps.safe_relpath
    sys = deps.sys
    # Bound parse-time allocation from the untrusted state to a PLAUSIBLE size
    # for the current caps (max_plan files × max_file_bytes, ×6 for worst-case
    # JSON escaping, + overhead) — big enough for any legit state, small enough
    # to refuse a bloated poisoned one.
    read_cap = max(max_plan, 1) * max(max_file_bytes or 200_000, 1) * 6 + 2_000_000
    try:
        with open(_build_state_path(root), encoding="utf-8") as fh:
            raw = fh.read(read_cap + 1)
            if len(raw) > read_cap:
                return None            # implausibly large state → discard
            st = json.loads(raw)
    except (OSError, json.JSONDecodeError):
        return None
    try:
        return _build_workflow.normalize_resume_state(
            st, task_sha=task_sha, root=root, max_plan=max_plan,
            max_file_bytes=max_file_bytes, safe_relpath=safe_relpath)
    except ValueError:
        print("ambient: previous build state contained unsafe paths — "
              "ignoring it and starting fresh", file=sys.stderr)
        return None
